In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from matplotlib import pyplot as plt
from sklearn import datasets
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

In [17]:
df=pd.read_csv("D:\\12345\\Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [28]:
df1=pd.get_dummies(df)
df1

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

     Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica  
0                      1                        0                       0  
1                      1                        0                       0  
2                      1                        0                       0  
3                      1                        0                       0  
4                      1                        0                       0  
..                   ...                      ...                     ...  
145                    0                        0                       1  
146                    0                        0                       1  
147                    0                        0                       1  
148                    0                        0                       1  
149                    0                        0                       1  

[150 rows x 8 columns]

In [16]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder

data = load_iris()

df = pd.DataFrame(data.data, columns=data.feature_names)

df['species'] = data.target

categorical_columns = ['species']

encoder = OneHotEncoder(drop='first', sparse=False)

encoded_data = encoder.fit_transform(df[categorical_columns])

encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(categorical_columns))
df = pd.concat([df, encoded_df], axis=1)

species_labels = {
    0: "Species_Iris-setosa",
    1: "Species_Iris-versicolor",
    2: "Species_Iris-virginica"
}

df['species_encoded'] = df['species'].map(species_labels)

df.drop(['species', 'species_encoded'], axis=1, inplace=True)

print(df)


     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species_1  species_2  

C:\Users\Abdul\python\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [29]:
import pandas as pd
import matplotlib.pyplot as plt


y_columns = df1.columns[-3:]
x_columns = df1.columns[2:6] 


y = df1[y_columns]
x = df1[x_columns]



In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=202)
print("TH shape of x_train is: ",x_train.shape)
print("TH shape of x_test is: ",x_test.shape)
print("TH shape of y_train is: ",y_train.shape)
print("TH shape of y_test is: ",y_test.shape)

TH shape of x_train is:  (120, 4)
TH shape of x_test is:  (30, 4)
TH shape of y_train is:  (120, 3)
TH shape of y_test is:  (30, 3)


In [31]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)
x_train_a=sc.transform(x_train)
x_test_a=sc.transform(x_test)

In [32]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='gini')
classifier.fit(x_train_a,y_train)

DecisionTreeClassifier()

In [33]:
classifier.score(x_test_a,y_test)

0.9666666666666667

In [34]:
predicted_prices = classifier.predict(x_test_a)
print(predicted_prices)

[[0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]]
